#ifndef LIBVIDEO_SAVER_FF_GLOBAL_H
#define LIBVIDEO_SAVER_FF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBVIDEO_SAVER_FF_LIBRARY)
#  define LIBVIDEO_SAVER_FFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBVIDEO_SAVER_FFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBVIDEO_SAVER_FF_GLOBAL_H
