#ifndef LIBVIDEOSAVER_GLOBAL_H
#define LIBVIDEOSAVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBVIDEOSAVER_LIBRARY)
#  define LIBVIDEOSAVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBVIDEOSAVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBVIDEOSAVER_GLOBAL_H
