/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-97504-g1128aa8-Reino"
#endif /* AVUTIL_FFVERSION_H */
